name: Release for new tag

# Controls when the action will run
on:
  # Triggers the workflow on push events but only for tags matching v*.*.*
  push:
    tags:
      - 'v*.*.*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg
        
      - name: Package Linux binary
        run: pkg . --target node18-linux-x64 --output dist/internal-chat-linux-x64
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: dist/internal-chat-linux-x64
          
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg
        
      - name: Package Windows binary
        run: pkg . --target node18-win-x64 --output dist/internal-chat-win-x64.exe
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: dist/internal-chat-win-x64.exe
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg
        
      - name: Package macOS binary
        run: pkg . --target node18-macos-x64 --output dist/internal-chat-macos-x64
        
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: dist/internal-chat-macos-x64

  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: dist
          
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: dist
          
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-binary
          path: dist
          
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/internal-chat-linux-x64
            dist/internal-chat-win-x64.exe
            dist/internal-chat-macos-x64
          token: ${{ secrets.GITHUB_TOKEN }}
